version: '3.3'

services:
  inventory-backend:
    image: inventory-backend
    build: ./Inventory-Management-Backend
    volumes:
      - ./data:/app/data
  inventory-frontend:
    image: inventory-frontend
    build: ./Inventory-Management
  nginx:
    image: nginx:latest
    ports:
      - 3000:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
